# Generated by Django 5.0.14 on 2026-01-10 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='The URL to bookmark', max_length=2048)),
                ('title', models.CharField(help_text='Title for the bookmark', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of the bookmark')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the bookmark was created')),
                ('user', models.ForeignKey(help_text='Owner of this bookmark', on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bookmark',
                'verbose_name_plural': 'Bookmarks',
                'ordering': ['-created_at'],
            },
        ),
    ]
